module.name=MFA factors - Login UI

totpui_authentication=TOTP Authentication

loginEmailFieldLabel=Email field label
loginPasswordFieldLabel=Password field label
loginSubmitButtonLabel=Login button label
loginBelowPasswordFieldHtml=Below-password area (HTML)
loginAdditionalActionHtml=Additional action area (HTML)
totpCodeVerificationFieldLabel=Authenticator code field label
totpCodeVerificationSubmitButtonLabel=Verify button label
totpCodeVerificationHelpHtml=Authenticator-code help text (HTML)
totpCodeVerificationBackupCodeHintHtml=Backup-code hint (HTML)
